language: java

jdk:
    - oraclejdk8

after_success:
    - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
    
deploy:
  provider: heroku
  api_key: 3b2dc8a3-67a0-47bc-9783-d05b051a6eea
  app: ciworkshop
